FROM nginx:latest
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY build /usr/share/nginx/html

# npm run build:kubernetes
# docker build -t lutando/laundry-frontend:latest -f Dockerfile .
# docker push lutando/laundry-frontend:latest