FROM nginxlatest
COPY nginx.conf etcnginxconf.ddefault.conf
COPY build usrsharenginxhtml

# in *.sln current working directory run these!
# docker build -t lutando/laundry-frontend:latest -f Dockerfile .
# docker push lutando/laundry-frontend:latest